USE [master]
GO

/****** Object:  Database [FPL_DaoTaoooo]    Script Date: 8/12/2023 3:22:50 AM ******/
CREATE DATABASE [FPL_DaoTaoooo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FPL_DaoTaoooo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\FPL_DaoTaoooo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FPL_DaoTaoooo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\FPL_DaoTaoooo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FPL_DaoTaoooo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FPL_DaoTaoooo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET ARITHABORT OFF 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET  ENABLE_BROKER 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET  MULTI_USER 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FPL_DaoTaoooo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FPL_DaoTaoooo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FPL_DaoTaoooo] SET QUERY_STORE = ON
GO

ALTER DATABASE [FPL_DaoTaoooo] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [FPL_DaoTaoooo] SET  READ_WRITE 
GO

